# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea833c9b204534d6724eeacca3042eea770388fc3355e0b450100292ca35215f56397976aa127e3ee405af25223f2ca9e7c48c046eb257444f828076b99ab8b8

test:
  secret_key_base: 8e451ef9bc3df57f5c1ce5a6bd0f6146d164137e5a5991b62c46042df1470208da6f354ff394ba75a145d7f9854f2e85b6782badea5b70295e00e994871b41a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
